a=("true")
b=("false")
print("-----------code:1")
print(a and b)
print(a and a)
print(b and b)
print("-----------code:2")
print(a or b)
print(a or a)
print(b or b)
print("-----------code:3")
print(a)
print(b)
